FROM apache/airflow:2.8.1

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY docker/requirements/airflow.txt .
RUN pip install --no-cache-dir --timeout=300 -r airflow.txt