FROM staywise/base:3.11

WORKDIR /app

# Tambahin postgresql-client buat psql di entrypoint
RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements/simulator.txt .
RUN pip install --no-cache-dir -r simulator.txt

COPY src/ ./src/

CMD ["/bin/bash", "/app/src/simulator/entrypoint.sh"]